### ISSUE TITLE
issue with model engine

### ISSUE THREAD

**Issue by wcdfilll** [Winds-Studio/Leaf#29]
[message (1).txt](https://github.com/Winds-Studio/Leaf/files/14543117/message.1.txt)

maybe issue by Gale

**Comment by Dreeam-qwq** [comment]
This issue has fixed in 1.20.4 branch of Leaf, but I will backport this fix to Leaf 1.19.4.

**Comment by Dreeam-qwq** [comment]
Fixed in 7654fc27454cac335567cfae437404cd775a3641

**Comment by zzzyyylllty** [comment]
是 Gale 的问题。
但是我在使用 Release 1.20.1 时仍然出现了这个错误。是没有对此版本进行兼容吗？

**Comment by Dreeam-qwq** [comment]
> 是 Gale 的问题。 但是我在使用 Release 1.20.1 时仍然出现了这个错误。是没有对此版本进行兼容吗？

1.20.1版本没做修复。为啥还在用这么老的子版本( 推荐用1.20.4或者1.21/1.21.1 (

**Comment by Dreeam-qwq** [comment]
> 私募网易只让用1.20.1（

不会考虑维护这么奇怪的版本，最多1.20.4
![image](https://github.com/user-attachments/assets/2307ca22-31bb-4f60-b706-27f15fb46d06)
